apiVersion: v1
kind: Service
metadata:
  name: api-main-service
  namespace: kitchen-sink
  labels:
    app: api-main
    app.kubernetes.io/name: api-main
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: api-main
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
