apiVersion: v1
kind: Service
metadata:
  name: api-second-service
  namespace: kitchen-sink
  labels:
    app: api-second
    app.kubernetes.io/name: api-second
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: api-second
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
